### ISSUE TITLE
Output is cropped in neovim

### ISSUE THREAD

**Issue by gavlooth** [arsenerei/vim-sayid#2]
I am using vim-sayid with neovim v0.2.0. While the workspace loads fine, the output of a depper trace (gsw) command is cropped after the first line.

**Comment by gavlooth** [comment]
The problem persists except from the initial sayid buffer
![screenshot from 2017-10-30 09-45-18](https://user-images.githubusercontent.com/10321050/32159679-2300eaf8-bd57-11e7-932f-7a8052b8470e.png) 
Deeper expressions:
![screenshot from 2017-10-30 09-45-28](https://user-images.githubusercontent.com/10321050/32159721-45d38a4a-bd57-11e7-85ef-d03bbb649568.png)
Tracing a function
![screenshot from 2017-10-30 09-45-42](https://user-images.githubusercontent.com/10321050/32159737-54d5b73e-bd57-11e7-9435-73359a367316.png)

**Comment by gavlooth** [comment]
Thanks for the effort, This tool could really help my workflow

**Comment by markwoodhall** [comment]
Weird,  I don't see that issue when working from `markwoodhall:master`. 

https://www.youtube.com/watch?v=TSCWzmYxBD8

**Comment by gavlooth** [comment]
I will try again, this time without merging the pull request

**Comment by gavlooth** [comment]
Indeed, Everything works perfectly now :)

Thanks again

**Comment by gavlooth** [comment]
Ok. Now there is another problem. ii doesnt work when on sayid buffer. Should i open another issue or is related to your modifications ?
After i open the syid buffer with gsw and hit ii, i get 

Error detected while processing function <SNR>43_query_id[3]..sayid#sayid_buf_query_id_w_mod[1]..sayid#call:                                                  
line    3:                                                                                                                                                    
E691: Can only compare List with List                                                                                                                         
E15: Invalid expression: get(response, 'value') != "" 

At least gsq works as expected !

**Comment by markwoodhall** [comment]
It looks like some kind of unexpected response is coming back from `fireplace#message(a:msg)[0]` in your case. I've just tried `gsw` and `ii` on a minimal use case and it works fine.
